### PR TITLE
Fix building mydumper on macOS

### LINKED ISSUE #22: mydumper doesn't build on macOS
macOS 10.14.4 (Mojave).

```
$ cmake . -DWITH_DOCS=OFF
-- Using mysql-config: /usr/local/bin/mysql_config
-- MySQL not found.
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/local/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLIB2_LIBRARIES (ADVANCED)
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
GTHREAD2_LIBRARIES (ADVANCED)
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
MYSQL_LIBRARIES_crypto
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
MYSQL_LIBRARIES_iconv
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
MYSQL_LIBRARIES_mariadb
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
MYSQL_LIBRARIES_ssl
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
MYSQL_LIBRARIES_z
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
ZLIB_LIBRARY
    linked by target "myloader" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper
    linked by target "mydumper" in directory /Users/kolbe/Devel/go/src/github.com/pingcap/mydumper

-- Configuring incomplete, errors occurred!
See also "/Users/kolbe/Devel/go/src/github.com/pingcap/mydumper/CMakeFiles/CMakeOutput.log".
```

After resolving that, `make` gives an error:
```
$ make
Scanning dependencies of target myloader
[ 10%] Building C object CMakeFiles/myloader.dir/myloader.c.o
[ 20%] Building C object CMakeFiles/myloader.dir/connection.c.o
[ 30%] Building C object CMakeFiles/myloader.dir/getPassword.c.o
[ 40%] Linking C executable myloader
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [myloader] Error 1
make[1]: *** [CMakeFiles/myloader.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by kolbe**
Fixes #22

### CODE REVIEW

**Comment by GregoryIan** [comment]
LGTM. @kennytm PTAL

**Comment by kennytm** [comment]
LGTM. Please sign the CLA @kolbe.

**Comment by kolbe** [comment]
@kennytm I've tried to sign it several times, and it always seems to complete successfully, but for some reason it isn't reflecting it on GitHub?

**Comment by gregwebs** [comment]
@kolbe I think you have to sign it once for every repo.

**Comment by kolbe** [comment]
@gregwebs you do. I did :-) Something is broken w/ the cli tool or how it's configured for this repo.

**Comment by kennytm** [comment]
Experiment with #26 suggests the CLA bot has been removed from this repo, so I'm going to merge ignoring the CLA status (which probably doesn't make sense anyway given this is a derived work).

**Pull request merged**
