### PR TITLE
mydumper: do write snapshot value when targeting TiDB

### PR DESCRIPTION
**Pull request by kennytm**

### CODE REVIEW

**Comment by kennytm** [comment]
@morgo @GregoryIan PTAL

Fixes issue [TOOL-446](https://internal.pingcap.net/jira/browse/TOOL-446).

**Comment by GregoryIan** [comment]
I think there are two problems,  I simulate logic of mydumper to explain them

- tidb_snapshot:  is a fuzzy position, it's a timestamp, not accurate TSO, does it matter?  or how can we convert tidb_snapshot to accurate TSO?  @morgo
- show master status: it seems to begin a new transaction and output it's start_ts of transaction,we can't write it into meta, it's not the consistency backup position that we want. right?


see examples

```mysql> select @@tidb_snapshot;
+-----------------+
| @@tidb_snapshot |
+-----------------+
|                 |
+-----------------+
1 row in set (0.00 sec)

mysql> show master status;
+-------------+--------------------+--------------+------------------+-------------------+
| File        | Position           | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+-------------+--------------------+--------------+------------------+-------------------+
| tidb-binlog | 403544618600497153 |              |                  |                   |
+-------------+--------------------+--------------+------------------+-------------------+
1 row in set (0.01 sec)

mysql> SET SESSION tidb_snapshot = "2018-10-13 11:10:31";
Query OK, 0 rows affected (0.00 sec)

mysql> show master status;
+-------------+--------------------+--------------+------------------+-------------------+
| File        | Position           | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+-------------+--------------------+--------------+------------------+-------------------+
| tidb-binlog | 403544624026877953 |              |                  |                   |
+-------------+--------------------+--------------+------------------+-------------------+
1 row in set (0.00 sec)

mysql> select @@tidb_snapshot;
+---------------------+
| @@tidb_snapshot     |
+---------------------+
| 2018-10-13 11:10:31 |
+---------------------+

mysql> show master status;
+-------------+--------------------+--------------+------------------+-------------------+
| File        | Position           | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+-------------+--------------------+--------------+------------------+-------------------+
| tidb-binlog | 403544637907402753 |              |                  |                   |
+-------------+--------------------+--------------+------------------+-------------------+
1 row in set (0.00 sec)

```

**Comment by morgo** [comment]
Sorry, I'm not sure of the answer to these questions.  I've asked the TiDB team :-)

**Comment by shenli** [comment]
That variable accepts TSO. See https://github.com/pingcap/tidb/pull/6749

**Comment by GregoryIan** [comment]
I think we need to set @@tidb_snapshot = `TSO`, we should do like:

1. get a `TSO` by `show master status`, assign this `TSO` to `tidb_snapshot`
2. use `tidb_snapshot` to set `tidb_snapshot variable of TiDB`
3. write tidb_snapshot into metadata file of MyDumper

what do you think of it @morgo @kennytm @shenli  (problem: how to get a consistency backup poin in MyDumper?)

**Comment by morgo** [comment]
I agree: I think we should do `show master status` then `tidb_snapshot` to the result.  This is more elegant than the current default, which is `NOW()- INTERVAL 1 SECOND`.

**Comment by kennytm** [comment]
@GregoryIan how would it interact with the custom snapshot value passed in via the `-z` flag? As your experiment have shown the result of `SHOW MASTER STATUS` doesn't respect `SET SESSION tidb_snapshot`

**Comment by GregoryIan** [comment]
@kennytm if we have custom snapshot, we don't need to  execute `show master status`. If we don't have custom snapshot, we only need to execute `show master status` in the beginning, and use it in all dumping process

**Comment by kennytm** [comment]
IMO the process would be like this:

1. If `-z` is undefined, query `SHOW MASTER STATUS` and use the `Position` as the `-z` value.
2. `SET SESSION tidb_snapshot = '%s'` using that `-z` value
3. Dump the following text into the metadata file:

    ```
    SHOW MASTER STATUS:
        Log: tidb-binlog
        Pos: %s
        GTID:
    ```

    The `%s` will be replaced by the `-z` value as-is, no matter the input is a TSO or a timestamp (e.g. `Pos: 2018-10-15 12:11:13`)

Would the consumer of the metadata understand a timestamp `Pos` correctly? Or should we forbid timestamp input and require a TSO be passed to `-z`?

**Comment by GregoryIan** [comment]
nice question! I think we should allow user to input both, and we give them a complete clear definition, how to use them in TiDB and Tools.

**Comment by kennytm** [comment]
@GregoryIan @morgo  PTAL again, the default `-z` value has been changed to the TSO provided by SHOW MASTER STATUS, and the `write_snapshot_info` is replaced by writing out `tidb_snapshot` directly. (We need to update the docs later)

**Comment by morgo** [comment]
+1 new methodology

**Comment by morgo** [comment]
Patch LGTM

**Comment by GregoryIan** [comment]
LGTM

**Pull request merged**
